/**
 * DevManagement — Admin section: Generate & manage developer accounts from GitHub contributors.
 * Route: /dashboard/developers
 *
 * Flow:
 *  1. Admin clicks "Generate Developers from GitHub"
 *  2. Fetches /repos/{owner}/{repo}/contributors using stored repo URL + token
 *  3. Auto-creates dev accounts with username@123 passwords
 *  4. Displays table with avatar, username, password (toggle show), contributions
 *  5. Admin can regenerate or click a dev to view their full GitHub profile
 */
import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTheme } from '../context/ThemeContext';
import { useAuth } from '../context/AuthContext';

const GH = 'https://api.github.com';

function parseRepoPath(url) {
  try {
    const clean = url.replace(/\.git$/, '').replace(/\/$/, '');
    const parts = clean.split('github.com/');
    if (parts.length < 2) return null;
    const segs = parts[1].split('/').filter(Boolean);
    if (segs.length < 2) return null;
    return `${segs[0]}/${segs[1]}`;
  } catch { return null; }
}

export default function DevManagement() {
  const { theme } = useTheme();
  const isDark = theme === 'dark';
  const navigate = useNavigate();
  const { adminUser, generateDevUsers, getAllDevUsers } = useAuth();

  const [devs,       setDevs]       = useState([]);
  const [generating, setGenerating] = useState(false);
  const [error,      setError]      = useState('');
  const [success,    setSuccess]    = useState('');
  const [search,     setSearch]     = useState('');
  const [showPassFor, setShowPassFor] = useState({});
  const [copied,     setCopied]     = useState('');

  const repoUrl   = localStorage.getItem('codepulse_repo_url') || adminUser?.repoUrl || '';
  const repoToken = adminUser?.githubToken || '';
  const repoPath  = parseRepoPath(repoUrl);

  // Load stored devs on mount
  useEffect(() => { setDevs(getAllDevUsers()); }, [getAllDevUsers]);

  const togglePass = (username) =>
    setShowPassFor((prev) => ({ ...prev, [username]: !prev[username] }));

  const copyToClipboard = (text, key) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(key);
      setTimeout(() => setCopied(''), 1500);
    });
  };

  const handleGenerate = useCallback(async () => {
    if (!repoPath) { setError('No GitHub repository connected. Please complete setup first.'); return; }
    setGenerating(true); setError(''); setSuccess('');
    try {
      const headers = { Accept: 'application/vnd.github+json' };
      if (repoToken) headers['Authorization'] = `Bearer ${repoToken}`;
      const r = await fetch(`${GH}/repos/${repoPath}/contributors?per_page=100&anon=false`, { headers });
      if (r.status === 404) throw new Error(`Repository "${repoPath}" not found or is private (add a GitHub token in setup).`);
      if (!r.ok) throw new Error(`GitHub API error: ${r.status} ${r.statusText}`);
      const contributors = await r.json();
      if (!Array.isArray(contributors) || contributors.length === 0) {
        throw new Error('No contributors found in this repository.');
      }
      const merged = generateDevUsers(contributors);
      setDevs(merged);
      setSuccess(`Generated ${contributors.length} developer account(s) from ${repoPath}`);
    } catch (e) {
      setError(e.message);
    } finally {
      setGenerating(false);
    }
  }, [repoPath, repoToken, generateDevUsers]);

  const filtered = devs.filter((d) =>
    d.username.toLowerCase().includes(search.toLowerCase()) ||
    (d.githubUsername || '').toLowerCase().includes(search.toLowerCase())
  );

  const autoCount   = devs.filter((d) => d.autoGenerated).length;
  const manualCount = devs.filter((d) => !d.autoGenerated).length;

  const cardCls  = `rounded-xl border ${isDark ? 'bg-[#141824] border-white/8' : 'bg-white border-gray-200'}`;
  const inputCls = `px-4 py-2.5 rounded-lg text-sm outline-none w-64 transition-colors ${
    isDark ? 'bg-[#1a1f2e] border border-white/8 text-white placeholder-slate-500 focus:border-emerald-500/40'
           : 'bg-white border border-gray-200 text-gray-900 placeholder-gray-400 focus:border-emerald-400'
  }`;

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <h1 className={`text-2xl font-bold ${isDark ? 'text-white' : 'text-gray-900'}`}>
            Developer Management
          </h1>
          <p className={`text-sm mt-1 ${isDark ? 'text-slate-400' : 'text-gray-500'}`}>
            {repoPath
              ? <>Connected repo: <span className="font-mono font-medium text-emerald-400">{repoPath}</span></>
              : <span className="text-yellow-400">⚠️ No repository connected — complete setup first</span>
            }
          </p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <button onClick={handleGenerate} disabled={generating || !repoPath}
            className={`px-5 py-2.5 rounded-xl text-sm font-semibold text-white flex items-center gap-2 transition-all duration-200 hover:scale-[1.02] hover:shadow-lg ${
              generating || !repoPath
                ? 'opacity-50 cursor-not-allowed bg-slate-600'
                : 'bg-gradient-to-r from-emerald-600 to-green-600 hover:shadow-emerald-500/20'
            }`}>
            {generating
              ? <><span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Fetching…</>
              : <><span>🚀</span> Generate Developers from GitHub</>
            }
          </button>
          {devs.length > 0 && (
            <button onClick={handleGenerate} disabled={generating}
              className={`px-4 py-2.5 rounded-xl text-sm font-medium border flex items-center gap-2 transition-colors ${
                isDark ? 'border-white/10 text-slate-300 hover:bg-white/5' : 'border-gray-200 text-gray-600 hover:bg-gray-50'
              }`}>
              🔄 Regenerate
            </button>
          )}
        </div>
      </div>

      {/* ── Alerts ── */}
      {error && (
        <div className={`p-4 rounded-xl text-sm font-medium border ${isDark ? 'bg-red-500/10 border-red-500/20 text-red-400' : 'bg-red-50 border-red-200 text-red-600'}`}>
          ⚠️ {error}
        </div>
      )}
      {success && (
        <div className={`p-4 rounded-xl text-sm font-medium border ${isDark ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : 'bg-emerald-50 border-emerald-200 text-emerald-700'}`}>
          ✅ {success}
        </div>
      )}

      {/* ── Stats row ── */}
      {devs.length > 0 && (
        <div className="grid grid-cols-3 gap-4">
          {[
            { label: 'Total Developers', value: devs.length,  color: 'text-emerald-400' },
            { label: 'Auto-Generated',   value: autoCount,    color: 'text-blue-400'    },
            { label: 'Manual Accounts',  value: manualCount,  color: 'text-purple-400'  },
          ].map((s) => (
            <div key={s.label} className={`${cardCls} p-4 text-center`}>
              <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
              <p className={`text-xs mt-0.5 ${isDark ? 'text-slate-500' : 'text-gray-400'}`}>{s.label}</p>
            </div>
          ))}
        </div>
      )}

      {/* ── Developer list ── */}
      {devs.length > 0 && (
        <div className={cardCls}>
          {/* Table header */}
          <div className={`flex items-center justify-between px-5 py-4 border-b ${isDark ? 'border-white/6' : 'border-gray-100'}`}>
            <h2 className={`text-sm font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>
              Developer Accounts ({filtered.length})
            </h2>
            <input value={search} onChange={(e) => setSearch(e.target.value)}
              placeholder="Search developers…" className={inputCls} />
          </div>

          {/* Table */}
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className={`text-xs font-semibold uppercase tracking-wider ${isDark ? 'text-slate-500' : 'text-gray-400'}`}>
                  {['Developer', 'Username', 'Password', 'Contributions', 'Actions'].map((h) => (
                    <th key={h} className={`px-5 py-3 text-left border-b ${isDark ? 'border-white/6' : 'border-gray-100'}`}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-white/4">
                {filtered.length === 0 ? (
                  <tr>
                    <td colSpan={5} className={`px-5 py-8 text-center text-sm ${isDark ? 'text-slate-500' : 'text-gray-400'}`}>
                      No developers match your search
                    </td>
                  </tr>
                ) : filtered.map((dev) => (
                  <tr key={dev.username}
                    className={`transition-colors ${isDark ? 'hover:bg-white/3' : 'hover:bg-gray-50/80'}`}>
                    {/* Avatar + name */}
                    <td className="px-5 py-3">
                      <div className="flex items-center gap-3">
                        {dev.avatarUrl ? (
                          <img src={dev.avatarUrl} alt={dev.username}
                            className="w-9 h-9 rounded-full ring-2 ring-emerald-500/20 flex-shrink-0" />
                        ) : (
                          <div className="w-9 h-9 rounded-full bg-gradient-to-br from-emerald-500 to-green-600 flex items-center justify-center text-sm text-white font-bold flex-shrink-0">
                            {dev.username[0].toUpperCase()}
                          </div>
                        )}
                        <div>
                          <p className={`text-sm font-medium ${isDark ? 'text-slate-200' : 'text-gray-800'}`}>{dev.username}</p>
                          {dev.autoGenerated && (
                            <span className={`text-[10px] font-medium px-1.5 py-0.5 rounded ${isDark ? 'bg-blue-500/15 text-blue-400' : 'bg-blue-50 text-blue-600'}`}>
                              auto
                            </span>
                          )}
                        </div>
                      </div>
                    </td>

                    {/* Username */}
                    <td className="px-5 py-3">
                      <div className="flex items-center gap-2">
                        <code className={`text-xs px-2 py-1 rounded font-mono ${isDark ? 'bg-white/5 text-slate-300' : 'bg-gray-100 text-gray-700'}`}>
                          {dev.username}
                        </code>
                        <button onClick={() => copyToClipboard(dev.username, `u-${dev.username}`)}
                          className={`text-xs transition-colors ${isDark ? 'text-slate-500 hover:text-slate-300' : 'text-gray-400 hover:text-gray-600'}`}
                          title="Copy username">
                          {copied === `u-${dev.username}` ? '✅' : '📋'}
                        </button>
                      </div>
                    </td>

                    {/* Password */}
                    <td className="px-5 py-3">
                      <div className="flex items-center gap-2">
                        <code className={`text-xs px-2 py-1 rounded font-mono ${isDark ? 'bg-white/5 text-slate-300' : 'bg-gray-100 text-gray-700'}`}>
                          {showPassFor[dev.username] ? dev.password : '••••••••'}
                        </code>
                        <button onClick={() => togglePass(dev.username)}
                          className={`text-xs transition-colors ${isDark ? 'text-slate-500 hover:text-slate-300' : 'text-gray-400 hover:text-gray-600'}`}
                          title="Toggle password">
                          {showPassFor[dev.username] ? '🙈' : '👁️'}
                        </button>
                        <button onClick={() => copyToClipboard(dev.password, `p-${dev.username}`)}
                          className={`text-xs transition-colors ${isDark ? 'text-slate-500 hover:text-slate-300' : 'text-gray-400 hover:text-gray-600'}`}
                          title="Copy password">
                          {copied === `p-${dev.username}` ? '✅' : '📋'}
                        </button>
                      </div>
                    </td>

                    {/* Contributions */}
                    <td className="px-5 py-3">
                      {dev.contributions != null ? (
                        <div className="flex items-center gap-2">
                          <div className={`w-16 h-1.5 rounded-full ${isDark ? 'bg-white/5' : 'bg-gray-100'}`}>
                            <div className="h-full rounded-full bg-emerald-500"
                              style={{ width: `${Math.min(100, (dev.contributions / (filtered[0]?.contributions || 1)) * 100)}%` }} />
                          </div>
                          <span className={`text-xs font-medium ${isDark ? 'text-slate-300' : 'text-gray-700'}`}>
                            {dev.contributions.toLocaleString()}
                          </span>
                        </div>
                      ) : (
                        <span className={`text-xs ${isDark ? 'text-slate-600' : 'text-gray-300'}`}>—</span>
                      )}
                    </td>

                    {/* Actions */}
                    <td className="px-5 py-3">
                      <button
                        onClick={() => navigate(`/dashboard/developers/${dev.githubUsername || dev.username}`)}
                        className={`text-xs font-medium px-3 py-1.5 rounded-lg transition-colors ${
                          isDark ? 'bg-white/5 hover:bg-white/10 text-slate-300' : 'bg-gray-100 hover:bg-gray-200 text-gray-700'
                        }`}>
                        View Profile →
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* ── Empty state ── */}
      {devs.length === 0 && !generating && (
        <div className={`${cardCls} p-14 text-center`}>
          <p className="text-5xl mb-4">👨‍💻</p>
          <h3 className={`text-xl font-bold mb-2 ${isDark ? 'text-white' : 'text-gray-900'}`}>No developers yet</h3>
          <p className={`text-sm mb-6 max-w-sm mx-auto ${isDark ? 'text-slate-400' : 'text-gray-500'}`}>
            Click <strong>"Generate Developers from GitHub"</strong> to automatically create developer accounts from your repository contributors.
          </p>
          {repoPath ? (
            <button onClick={handleGenerate}
              className="px-6 py-3 rounded-xl text-sm font-semibold text-white bg-gradient-to-r from-emerald-600 to-green-600 hover:shadow-lg hover:shadow-emerald-500/20 transition-all duration-200 hover:scale-[1.02]">
              🚀 Generate Developers from GitHub
            </button>
          ) : (
            <p className={`text-sm ${isDark ? 'text-yellow-400' : 'text-yellow-600'}`}>
              ⚠️ Connect a repository in Settings first
            </p>
          )}
        </div>
      )}
    </div>
  );
}
