/**
 * AuthContext — Admin + Developer auth store.
 *
 * Admin shape  (cp_admin_users):   { email, password, isSetupComplete, repoUrl, githubToken, createdAt }
 * Developer shape (cp_dev_users):  { username, email, password, githubUsername, avatarUrl,
 *                                    contributions, autoGenerated, createdAt }
 *
 * Sessions: cp_admin_session, cp_dev_session, cp_role
 */
import React, { createContext, useContext, useState, useCallback } from 'react';

const ADMIN_USERS_KEY = 'cp_admin_users';
const ADMIN_SES_KEY   = 'cp_admin_session';
const DEV_USERS_KEY   = 'cp_dev_users';
const DEV_SES_KEY     = 'cp_dev_session';
const ROLE_KEY        = 'cp_role';

const loadJSON  = (key) => { try { return JSON.parse(localStorage.getItem(key) || '[]'); } catch { return []; } };
const saveJSON  = (key, val) => localStorage.setItem(key, JSON.stringify(val));

const loadAdminUsers = () => loadJSON(ADMIN_USERS_KEY);
const saveAdminUsers = (u) => saveJSON(ADMIN_USERS_KEY, u);
const loadDevUsers   = () => loadJSON(DEV_USERS_KEY);
const saveDevUsers   = (u) => saveJSON(DEV_USERS_KEY, u);

/* ── startup validation ─────────────────────────────────────────── */
function initSession() {
  const storedRole       = localStorage.getItem(ROLE_KEY);
  const storedAdminEmail = localStorage.getItem(ADMIN_SES_KEY);
  const storedDevEmail   = localStorage.getItem(DEV_SES_KEY);

  if (storedRole === 'admin') {
    const users = loadAdminUsers();
    const valid = storedAdminEmail && users.find((u) => u.email === storedAdminEmail);
    if (!valid) {
      localStorage.removeItem(ROLE_KEY); localStorage.removeItem(ADMIN_SES_KEY);
      return { role: null, adminEmail: null, devEmail: null };
    }
    return { role: 'admin', adminEmail: storedAdminEmail, devEmail: null };
  }
  if (storedRole === 'developer') {
    const devs  = loadDevUsers();
    const valid = storedDevEmail && devs.find((d) => d.email === storedDevEmail);
    if (!valid) {
      localStorage.removeItem(ROLE_KEY); localStorage.removeItem(DEV_SES_KEY);
      return { role: null, adminEmail: null, devEmail: null };
    }
    return { role: 'developer', adminEmail: null, devEmail: storedDevEmail };
  }
  return { role: null, adminEmail: null, devEmail: null };
}

const AuthContext = createContext(null);

export function AuthProvider({ children }) {
  const init = initSession();
  const [role,       setRole]       = useState(init.role);
  const [adminEmail, setAdminEmail] = useState(init.adminEmail);
  const [devEmail,   setDevEmail]   = useState(init.devEmail);

  const getAdminUser = useCallback(() => {
    if (!adminEmail) return null;
    return loadAdminUsers().find((u) => u.email === adminEmail) || null;
  }, [adminEmail]);

  const getDevUser = useCallback(() => {
    if (!devEmail) return null;
    const devs = loadDevUsers();
    return devs.find((d) => d.email === devEmail) || null;
  }, [devEmail]);

  /* ── ADMIN ──────────────────────────────────────────────────── */
  const adminSignUp = useCallback((email, password) => {
    const users = loadAdminUsers();
    if (users.find((u) => u.email.toLowerCase() === email.toLowerCase())) {
      return { success: false, error: 'An account with this email already exists.' };
    }
    const newUser = {
      email: email.toLowerCase().trim(), password,
      isSetupComplete: false, repoUrl: '', githubToken: '',
      createdAt: new Date().toISOString(),
    };
    saveAdminUsers([...users, newUser]);
    localStorage.setItem(ADMIN_SES_KEY, newUser.email);
    localStorage.setItem(ROLE_KEY, 'admin');
    setAdminEmail(newUser.email); setRole('admin');
    return { success: true, user: newUser };
  }, []);

  const adminSignIn = useCallback((email, password) => {
    const users = loadAdminUsers();
    const user  = users.find((u) => u.email.toLowerCase() === email.toLowerCase().trim());
    if (!user)                    return { success: false, error: 'No account found with this email.' };
    if (user.password !== password) return { success: false, error: 'Incorrect password.' };
    localStorage.setItem(ADMIN_SES_KEY, user.email);
    localStorage.setItem(ROLE_KEY, 'admin');
    setAdminEmail(user.email); setRole('admin');
    return { success: true, user };
  }, []);

  const logout = useCallback(() => {
    localStorage.removeItem(ADMIN_SES_KEY);
    localStorage.removeItem(ROLE_KEY);
    setAdminEmail(null); setRole(null);
  }, []);

  const completeSetup = useCallback((repoUrl, githubToken) => {
    const email   = localStorage.getItem(ADMIN_SES_KEY);
    const updated = loadAdminUsers().map((u) =>
      u.email === email ? { ...u, isSetupComplete: true, repoUrl, githubToken } : u
    );
    saveAdminUsers(updated);
    setAdminEmail((e) => e);
  }, []);

  /* ── DEVELOPER ──────────────────────────────────────────────── */

  /** Sign In — match by username (primary) or email */
  const devSignIn = useCallback((usernameOrEmail, password) => {
    const devs = loadDevUsers();
    const key  = usernameOrEmail.toLowerCase().trim();
    const user = devs.find(
      (d) => d.username.toLowerCase() === key ||
             (d.email && d.email.toLowerCase() === key)
    );
    if (!user)                    return { success: false, error: 'No developer account found. Contact your admin.' };
    if (user.password !== password) return { success: false, error: 'Incorrect password.' };
    const sessionEmail = user.email || `${user.username}@github.com`;
    localStorage.setItem(DEV_SES_KEY, sessionEmail);
    localStorage.setItem(ROLE_KEY, 'developer');
    setDevEmail(sessionEmail); setRole('developer');
    return { success: true, user };
  }, []);

  /** Bulk-generate dev accounts from GitHub contributors (admin only).
   *  Auto-assigns: password = `${login}@123`. Merges with existing manual accounts. */
  const generateDevUsers = useCallback((contributors) => {
    const existing  = loadDevUsers().filter((d) => !d.autoGenerated);
    const generated = contributors.map((c) => ({
      username:       c.login,
      email:          `${c.login}@github.com`,
      password:       `${c.login}@123`,
      githubUsername: c.login,
      avatarUrl:      c.avatar_url,
      contributions:  c.contributions,
      autoGenerated:  true,
      createdAt:      new Date().toISOString(),
    }));
    // Existing manual devs take priority over auto-generated ones
    const autoFiltered = generated.filter(
      (g) => !existing.find((e) => e.username.toLowerCase() === g.username.toLowerCase())
    );
    const merged = [...existing, ...autoFiltered];
    saveDevUsers(merged);
    return merged;
  }, []);

  const devLogout = useCallback(() => {
    localStorage.removeItem(DEV_SES_KEY);
    localStorage.removeItem(ROLE_KEY);
    setDevEmail(null); setRole(null);
  }, []);

  const updateDevProfile = useCallback((updates) => {
    const email   = localStorage.getItem(DEV_SES_KEY);
    const updated = loadDevUsers().map((d) =>
      d.email === email ? { ...d, ...updates } : d
    );
    saveDevUsers(updated);
    setDevEmail((e) => e);
    return { success: true };
  }, []);

  /* ── Shared / fallback ──────────────────────────────────────── */
  const login = useCallback((selectedRole) => {
    localStorage.setItem(ROLE_KEY, selectedRole);
    setRole(selectedRole);
  }, []);

  const adminUser = getAdminUser();
  const devUser   = getDevUser();

  return (
    <AuthContext.Provider value={{
      role,
      /* Admin */
      adminEmail, adminUser,
      isAdmin:         role === 'admin',
      isSetupComplete: adminUser?.isSetupComplete ?? false,
      adminSignUp, adminSignIn, logout, completeSetup,
      /* Developer */
      devEmail, devUser,
      isDeveloper:   role === 'developer',
      devSignIn, devLogout, generateDevUsers, updateDevProfile,
      /* Shared */
      isLoggedIn:    !!role,
      login,
      /* Admin helper */
      getAllDevUsers: loadDevUsers,
    }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used inside <AuthProvider>');
  return ctx;
}
